spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_center?nullCatalogMeansCurrent=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # >= 5.x com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: 1
          target-version: 1
  application:
    name: user-center
server:
  port: 8083

